# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a01ad2392af9dbe183163bd8e5d062b8"
name = "cut-the-size"
handle = "cut-the-size"
application_url = "https://styles-photos-thesis-ladies.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://styles-photos-thesis-ladies.trycloudflare.com/auth/callback", "https://styles-photos-thesis-ladies.trycloudflare.com/auth/shopify/callback", "https://styles-photos-thesis-ladies.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
